<h4><center>About Dataset</h4></center>
This dataset generated by respondents to a distributed survey via Amazon Mechanical Turk between 03.12.2016-05.12.2016. Thirty eligible Fitbit users consented to the submission of personal tracker data, including minute-level output for physical activity, heart rate, and sleep monitoring. Individual reports can be parsed by export session ID (column A) or timestamp (column B). Variation between output represents use of different types of Fitbit trackers and individual tracking behaviors / preferences.

<center><h3>Análise exploratória dados fitbit</center></h3>

In [228]:
import pandas as pd
from pathlib import Path

In [229]:
# This facility open the file,  wihout pass all the file path, because there are two people coding this project.
caminho_arquivo = Path('dailyActivity_merged.csv').resolve().parents[1]
print('caminho do diretório',caminho_arquivo)

caminho do diretório C:\Users\niniv\OneDrive\Área de Trabalho\bellabeat-analysis


In [230]:
d_activity = pd.read_csv(f'{caminho_arquivo}/database/fitbit-data/dailyActivity_merged.csv')
heartrate = pd.read_csv(f'{caminho_arquivo}/database/fitbit-data/heartrate_seconds_merged.csv')
h_calories = pd.read_csv(f'{caminho_arquivo}/database/fitbit-data/hourlyCalories_merged.csv')
h_intensity = pd.read_csv(f'{caminho_arquivo}/database/fitbit-data/hourlyIntensities_merged.csv')
m_calories = pd.read_csv(f'{caminho_arquivo}/database/fitbit-data/minuteCaloriesNarrow_merged.csv')
m_intensity = pd.read_csv(f'{caminho_arquivo}/database/fitbit-data/minuteIntensitiesNarrow_merged.csv')
m_sleep = pd.read_csv(f'{caminho_arquivo}//database/fitbit-data/minuteSleep_merged.csv')
weightlog = pd.read_csv(f'{caminho_arquivo}/database/fitbit-data/weightLogInfo_merged_treated.csv')

### Análise exploratória d_activity


In [231]:
d_activity.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 457 entries, 0 to 456
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Id                        457 non-null    int64  
 1   ActivityDate              457 non-null    object 
 2   TotalSteps                457 non-null    int64  
 3   TotalDistance             457 non-null    float64
 4   TrackerDistance           457 non-null    float64
 5   LoggedActivitiesDistance  457 non-null    float64
 6   VeryActiveDistance        457 non-null    float64
 7   ModeratelyActiveDistance  457 non-null    float64
 8   LightActiveDistance       457 non-null    float64
 9   SedentaryActiveDistance   457 non-null    float64
 10  VeryActiveMinutes         457 non-null    int64  
 11  FairlyActiveMinutes       457 non-null    int64  
 12  LightlyActiveMinutes      457 non-null    int64  
 13  SedentaryMinutes          457 non-null    int64  
 14  Calories  

In [232]:
# Total de linhas no data frame dailyActivity 
contagem_linhas = d_activity.shape[0]  # Zero representa as linhas
contagem_linhas


457

In [233]:
d_activity['Id'].nunique() #35 ids nos dados de d_activity


35

In [234]:
# Existe 457 registros, mas 35 Ids unicos, Sempre que a pessoa usa o app o registro é salvo novamente.
# Isso é uma suposição, então se for analisar quantidade de atividade fisica por pessoa, tem  que juntar os id.
# Se for analisar a quantidade de que pessoa usa o app, junta quantas vezes tal id aparece.
# Apenas um exemplo
duplicados = d_activity['Id'].duplicated().sum()
duplicados


422

In [235]:
# Mostrando Ids duplicados, Então, sempre que a pessoa usa o app grava o dia e a data da atividade.
# existe apenas 35 pessoas que usam o app. 
duplicados = d_activity.duplicated(subset='Id')
print(d_activity[duplicados])

             Id ActivityDate  TotalSteps  TotalDistance  TrackerDistance  \
1    1503960366    3/26/2016       17609      11.550000        11.550000   
2    1503960366    3/27/2016       12736       8.530000         8.530000   
3    1503960366    3/28/2016       13231       8.930000         8.930000   
4    1503960366    3/29/2016       12041       7.850000         7.850000   
5    1503960366    3/30/2016       10970       7.160000         7.160000   
..          ...          ...         ...            ...              ...   
452  8877689391     4/8/2016       23014      20.389999        20.389999   
453  8877689391     4/9/2016       16470       8.070000         8.070000   
454  8877689391    4/10/2016       28497      27.530001        27.530001   
455  8877689391    4/11/2016       10622       8.060000         8.060000   
456  8877689391    4/12/2016        2350       1.780000         1.780000   

     LoggedActivitiesDistance  VeryActiveDistance  ModeratelyActiveDistance  \
1       

In [236]:
# Quantas vezes os 35 id aparecem, para saber frequência do uso do app 
contagem_id = d_activity['Id'].value_counts()
contagem_id

Id
4057192912    32
4020332650    32
1503960366    19
1624580081    19
2347167796    15
4702921684    15
4445114986    15
6962181067    14
2320127002    12
4558609924    12
8792009665    12
8378563200    12
8253242879    12
7086361926    12
7007744171    12
2026352035    12
5553957443    12
8877689391    12
1844505072    12
2022484408    12
2873212765    12
3977333714    12
1927972279    12
4319703577    12
8053475328    11
5577150313    11
6290855005    10
1644430081    10
6117666160    10
3372868164    10
6391747486     9
6775888955     9
2891001357     8
8583815059     8
4388161847     8
Name: count, dtype: int64

In [237]:
d_activity.head()

Id ActivityDate  TotalSteps  TotalDistance  TrackerDistance  \
0  1503960366    3/25/2016       11004           7.11             7.11   
1  1503960366    3/26/2016       17609          11.55            11.55   
2  1503960366    3/27/2016       12736           8.53             8.53   
3  1503960366    3/28/2016       13231           8.93             8.93   
4  1503960366    3/29/2016       12041           7.85             7.85   

   LoggedActivitiesDistance  VeryActiveDistance  ModeratelyActiveDistance  \
0                       0.0                2.57                      0.46   
1                       0.0                6.92                      0.73   
2                       0.0                4.66                      0.16   
3                       0.0                3.19                      0.79   
4                       0.0                2.16                      1.09   

   LightActiveDistance  SedentaryActiveDistance  VeryActiveMinutes  \
0                 4.07                      0.0                 33   
1                 3.91                      0.0                 89   
2                 3.71                      0.0                 56   
3                 4.95                      0.0                 39   
4                 4.61                      0.0                 28   

   FairlyActiveMinutes  LightlyActiveMinutes  SedentaryMinutes  Calories  
0                   12                   205               804      1819  
1                   17                   274               588      2154  
2                    5                   268               605      1944  
3                   20                   224              1080      1932  
4                   28                   243               763      1886

### Análise Total steps

#### Estatística dos dados de passos

In [238]:
d_activity['TotalSteps'].median() #5986.0
d_activity['TotalSteps'].mean() #6546.5
d_activity['TotalSteps'].mode() #0  61 linhas desse dataframe não tem nenhuma entrada de exercício, ou passos. 
#396 entradas com input de passos

0    0
Name: TotalSteps, dtype: int64

#### Análise de passos max e mean por id

In [239]:
pd.pivot_table(d_activity, values = 'TotalSteps', index= 'Id', aggfunc= ('mean', 'max')).round(2)
#apenas uma pessoa não fez input de passos, média e máximo de passos parece sem erros

max      mean
Id                         
1503960366  17609  11640.53
1624580081  18464   4226.26
1644430081  20237   9274.80
1844505072   6847   3640.58
1927972279   5662   2180.83
2022484408  18247  12174.92
2026352035   6679   3392.75
2320127002  11230   3138.42
2347167796  16081   9800.07
2873212765  14103   6636.58
2891001357   4126    773.62
3372868164   8827   6127.50
3977333714  15425   8663.92
4020332650  12483   5776.59
4057192912   8433   1887.22
4319703577  10946   7820.58
4388161847      0      0.00
4445114986   6911   4293.07
4558609924   8828   5785.25
4702921684  14002   7943.40
5553957443  15444   8354.75
5577150313  14873   8608.18
6117666160  19658   8248.60
6290855005   9548   1618.10
6391747486   9766   1336.89
6775888955  13987   5559.00
6962181067  18952  12639.71
7007744171  16806  12260.33
7086361926  14604   6103.92
8053475328  25701  14844.36
8253242879  12026   2389.92
8378563200  14179   8135.25
8583815059   6835   3045.50
8792009665   8452   3094.92
8877689391  28497  17417.08

In [240]:
d_activity[d_activity['TotalSteps']== 0] #dados nulos? é possível entender que essas pessoas só usam o fitbit em dias de exercício?

Id ActivityDate  TotalSteps  TotalDistance  TrackerDistance  \
51   1844505072     4/4/2016           0            0.0              0.0   
52   1844505072     4/5/2016           0            0.0              0.0   
59   1844505072    4/12/2016           0            0.0              0.0   
96   2320127002     4/1/2016           0            0.0              0.0   
97   2320127002     4/2/2016           0            0.0              0.0   
..          ...          ...         ...            ...              ...   
402  8253242879     4/2/2016           0            0.0              0.0   
403  8253242879     4/3/2016           0            0.0              0.0   
404  8253242879     4/4/2016           0            0.0              0.0   
405  8253242879     4/5/2016           0            0.0              0.0   
412  8253242879    4/12/2016           0            0.0              0.0   

     LoggedActivitiesDistance  VeryActiveDistance  ModeratelyActiveDistance  \
51                        0.0                 0.0                       0.0   
52                        0.0                 0.0                       0.0   
59                        0.0                 0.0                       0.0   
96                        0.0                 0.0                       0.0   
97                        0.0                 0.0                       0.0   
..                        ...                 ...                       ...   
402                       0.0                 0.0                       0.0   
403                       0.0                 0.0                       0.0   
404                       0.0                 0.0                       0.0   
405                       0.0                 0.0                       0.0   
412                       0.0                 0.0                       0.0   

     LightActiveDistance  SedentaryActiveDistance  VeryActiveMinutes  \
51                   0.0                      0.0                  0   
52                   0.0                      0.0                  0   
59                   0.0                      0.0                  0   
96                   0.0                      0.0                  0   
97                   0.0                      0.0                  0   
..                   ...                      ...                ...   
402                  0.0                      0.0                  0   
403                  0.0                      0.0                  0   
404                  0.0                      0.0                  0   
405                  0.0                      0.0                  0   
412                  0.0                      0.0                  0   

     FairlyActiveMinutes  LightlyActiveMinutes  SedentaryMinutes  Calories  
51                     0                     0               669      1347  
52                     0                     0              1440      1347  
59                     0                     0               426       399  
96                     0                     0              1440      1324  
97                     0                     0              1440      1324  
..                   ...                   ...               ...       ...  
402                    0                     0              1440      1429  
403                    0                     0              1440      1429  
404                    0                     0              1440      1429  
405                    0                     0              1440      1429  
412                    0                     0              1440         0  

[61 rows x 15 columns]

In [241]:
# pesquisando entradas dos ids com steps nulos - 14 pessoas com dados nulos de passos - sabendo que apenas um desses Ids (4388161847) não tem nenhum input de passos
null_steps_ids = d_activity.loc[d_activity['TotalSteps']== 0, 'Id'].drop_duplicates()
null_steps_ids

51     1844505072
96     2320127002
122    2347167796
134    2873212765
135    2891001357
197    4057192912
240    4319703577
241    4388161847
290    4702921684
316    6117666160
326    6290855005
334    6391747486
346    6775888955
401    8253242879
Name: Id, dtype: int64

### Insights sobre steps até aqui:
* 34 Ids tem input de passos, sem dados discrepantes.
* um Id não inputou passos nenhuma vez.
* 14 ids tem dias com 0 passos, como não é viável passar 1 dia sem dar passos, pode-se supor que são pessoas que não usam o fit bit em dias sem exercício (e nessa amostra, são minoria)

In [242]:
# existe 14 ids com steps zero, mas todas as suas colunas nao estão com zero, saber qual conteudo das colunas dos ids com steps zro
id_a_verificar = [
    1844505072, 2320127002, 2347167796, 2873212765, 2891001357,
    4057192912, 4319703577, 4388161847, 4702921684, 6117666160,
    6290855005, 6391747486, 6775888955, 8253242879
]
for ids in id_a_verificar:
    print(f"Verificando se o ID {ids}")
    colunas_id = d_activity[d_activity['Id'] == ids].drop('Id', axis=1)
    
    # Check if all values in all columns (except 'Id') are zero
    todas_zeros = (colunas_id == 0).all().all()
    print("todas as suas colunas tem valor zero", todas_zeros)

Verificando se o ID 1844505072
todas as suas colunas tem valor zero False
Verificando se o ID 2320127002
todas as suas colunas tem valor zero False
Verificando se o ID 2347167796
todas as suas colunas tem valor zero False
Verificando se o ID 2873212765
todas as suas colunas tem valor zero False
Verificando se o ID 2891001357
todas as suas colunas tem valor zero False
Verificando se o ID 4057192912
todas as suas colunas tem valor zero False
Verificando se o ID 4319703577
todas as suas colunas tem valor zero False
Verificando se o ID 4388161847
todas as suas colunas tem valor zero False
Verificando se o ID 4702921684
todas as suas colunas tem valor zero False
Verificando se o ID 6117666160
todas as suas colunas tem valor zero False
Verificando se o ID 6290855005
todas as suas colunas tem valor zero False
Verificando se o ID 6391747486
todas as suas colunas tem valor zero False
Verificando se o ID 6775888955
todas as suas colunas tem valor zero False
Verificando se o ID 8253242879
todas a

In [243]:
# Ver contéudo das colunas desse ID 1844505072
d_activity[d_activity['Id']== 1844505072]

Id ActivityDate  TotalSteps  TotalDistance  TrackerDistance  \
48  1844505072     4/1/2016        6847           4.53             4.53   
49  1844505072     4/2/2016        5367           3.55             3.55   
50  1844505072     4/3/2016        2841           1.88             1.88   
51  1844505072     4/4/2016           0           0.00             0.00   
52  1844505072     4/5/2016           0           0.00             0.00   
53  1844505072     4/6/2016           7           0.00             0.00   
54  1844505072     4/7/2016        6344           4.19             4.19   
55  1844505072     4/8/2016        5316           3.51             3.51   
56  1844505072     4/9/2016        4979           3.29             3.29   
57  1844505072    4/10/2016        6556           4.34             4.34   
58  1844505072    4/11/2016        5430           3.59             3.59   
59  1844505072    4/12/2016           0           0.00             0.00   

    LoggedActivitiesDistance  VeryActiveDistance  ModeratelyActiveDistance  \
48                       0.0                0.61                      0.37   
49                       0.0                0.00                      0.00   
50                       0.0                0.00                      0.00   
51                       0.0                0.00                      0.00   
52                       0.0                0.00                      0.00   
53                       0.0                0.00                      0.00   
54                       0.0                0.00                      0.00   
55                       0.0                0.00                      0.00   
56                       0.0                0.00                      0.00   
57                       0.0                0.00                      0.00   
58                       0.0                0.00                      0.00   
59                       0.0                0.00                      0.00   

    LightActiveDistance  SedentaryActiveDistance  VeryActiveMinutes  \
48                 3.55                      0.0                  9   
49                 3.55                      0.0                  0   
50                 1.88                      0.0                  0   
51                 0.00                      0.0                  0   
52                 0.00                      0.0                  0   
53                 0.00                      0.0                  0   
54                 4.19                      0.0                  0   
55                 3.51                      0.0                  0   
56                 3.29                      0.0                  0   
57                 4.33                      0.0                  0   
58                 3.59                      0.0                  0   
59                 0.00                      0.0                  0   

    FairlyActiveMinutes  LightlyActiveMinutes  SedentaryMinutes  Calories  
48                    9                   251              1171      1969  
49                    0                   263              1177      1889  
50                    0                   136              1114      1636  
51                    0                     0               669      1347  
52                    0                     0              1440      1347  
53                    0                     1              1439      1349  
54                    0                   290              1150      1965  
55                    0                   221              1219      1824  
56                    0                   184               620      1807  
57                    0                   305               810      1971  
58                    0                   251              1189      1888  
59                    0                     0               426       399

In [244]:
# Quantas vezes o step zero aparece 
df_filtrado = d_activity[d_activity['TotalSteps'] == 0]
len(df_filtrado['TotalSteps'])
# Existe 61 valores com zero, alguns dos 14 ids com valores zero, não 

61

### Acrescentando infomação na Análise do  d_activity
* 14 ids tem dias com 0 passos, como não é viável passar 1 dia sem dar passos, <br>pode-se supor que são pessoas que não usam o fit bit em dias sem exercício <br>(e nessa amostra, são minoria)
desses 14 ids, alguns repetem com passos 0 em outros dias.
* Há um total de 61 registros com passados zeros, esses são os 14 ids que contém essa situação.

* Como a base tem 427 registros e 35 ids unicos foi verificado que <br>apenas 61 registros contém steps com 0.
Grande parte dos 35 ids costumam usam o app?  

### Análise exploratória heartrate

In [245]:
heartrate.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1154681 entries, 0 to 1154680
Data columns (total 3 columns):
 #   Column  Non-Null Count    Dtype 
---  ------  --------------    ----- 
 0   Id      1154681 non-null  int64 
 1   Time    1154681 non-null  object
 2   Value   1154681 non-null  int64 
dtypes: int64(2), object(1)
memory usage: 26.4+ MB


In [246]:
heartrate.head()

Id                 Time  Value
0  2022484408  4/1/2016 7:54:00 AM     93
1  2022484408  4/1/2016 7:54:05 AM     91
2  2022484408  4/1/2016 7:54:10 AM     96
3  2022484408  4/1/2016 7:54:15 AM     98
4  2022484408  4/1/2016 7:54:20 AM    100

In [247]:
heartrate['Id'].nunique() #14 ids com heartrate, menos que a metade dos dados de passos

14

In [248]:
# Total de linhas no data frame heartrate
contagem_linhas = heartrate.shape[0]  # Zero representa as linhas
contagem_linhas
# Tem bem mais registros que o dailyactivity 

1154681

In [249]:
pd.pivot_table(heartrate, values = 'Value', index= 'Id', aggfunc= ['mean', 'max', 'min']).round(2).sort_values(by= ('mean', 'Value'), ascending= False)

mean   max   min
            Value Value Value
Id                           
6775888955  97.74   185    59
7007744171  89.93   158    56
8877689391  87.60   179    47
6391747486  84.12   133    49
6117666160  83.49   130    52
4020332650  81.90   151    46
2022484408  81.69   182    46
6962181067  80.69   176    48
4558609924  79.55   158    50
8792009665  76.33   163    45
2347167796  76.07   182    51
5553957443  69.42   152    48
2026352035  65.78    80    57
5577150313  65.00   176    36

### Insights até aqui
* apenas 14 ids tem input de heart rate
* destes 14, 4 ids estão em comum com a lista de pessoas que teorizei que só usam durante exercício (6775888955 , 6391747486, 6117666160 , 2347167796), o que ainda pode fazer sentido, a valor médio de batimentos é alto em 3 delas - pode indicar novamente fitbit apenas quando faz exercício
* Tem menos ids e mais registros que o dailyActivit

* OBS ( Seria bom depois ver os ids que usa dailyactivit e ver quais ids são iguais que utiliza o heartrate, dos 14 ids, ver quais são esses do dailyactivit, pois ir juntando, pode ajudar a tirar alguma análise, da saúde deles )

In [250]:
# Quantas vezes os 14 id aparecem, para saber frequência do uso do app 
contagem_id = heartrate['Id'].value_counts()
contagem_id

Id
4020332650    283794
6962181067    125875
2347167796    120804
5553957443     97797
5577150313     87649
8877689391     85115
8792009665     70087
4558609924     69339
7007744171     64786
2022484408     56483
6117666160     53666
6775888955     35100
6391747486      3747
2026352035       439
Name: count, dtype: int64

### Análise exploratória hourly calories
* 34 ids tem input de calorias

In [251]:
h_calories.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24084 entries, 0 to 24083
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Id            24084 non-null  int64 
 1   ActivityHour  24084 non-null  object
 2   Calories      24084 non-null  int64 
dtypes: int64(2), object(1)
memory usage: 564.6+ KB


In [252]:
h_calories.head()

Id           ActivityHour  Calories
0  1503960366  3/12/2016 12:00:00 AM        48
1  1503960366   3/12/2016 1:00:00 AM        48
2  1503960366   3/12/2016 2:00:00 AM        48
3  1503960366   3/12/2016 3:00:00 AM        48
4  1503960366   3/12/2016 4:00:00 AM        48

In [253]:
h_calories['Id'].nunique() #34 ids com input de calorias (gastas)

34

In [254]:
h_calories['ActivityDay'] = h_calories['ActivityHour'].str.extract(r'^([^\s]+)')

daily_calories = pd.pivot_table(h_calories, values= 'Calories', index= ('Id', 'ActivityDay'), aggfunc= 'sum')
daily_calories

Calories
Id         ActivityDay          
1503960366 3/12/2016        2228
           3/13/2016        2100
           3/14/2016        1830
           3/15/2016        2111
           3/16/2016        1967
...                          ...
8877689391 4/5/2016         2832
           4/6/2016         4034
           4/7/2016         2941
           4/8/2016         4191
           4/9/2016         3835

[1021 rows x 1 columns]

In [255]:
avg_daily_calories = pd.pivot_table(daily_calories, values = 'Calories', index='Id', aggfunc= 'mean').round(2).sort_values(by='Calories', ascending= False)
avg_daily_calories

Calories
Id                  
8877689391   3435.25
5577150313   3434.71
8378563200   3338.84
4702921684   2957.23
1644430081   2956.90
8053475328   2941.59
6290855005   2652.27
4020332650   2633.62
6775888955   2631.03
7007744171   2609.22
1927972279   2580.94
2022484408   2568.50
7086361926   2292.34
8583815059   2286.64
6117666160   2270.83
4445114986   2192.34
6962181067   2170.50
4319703577   2144.29
2347167796   2093.41
1503960366   1945.94
2873212765   1906.90
8792009665   1901.50
3372868164   1900.03
4057192912   1895.72
6391747486   1805.21
5553957443   1767.94
4558609924   1764.34
8253242879   1495.13
1844505072   1471.81
2026352035   1452.91
2320127002   1444.88
1624580081   1384.22
3977333714   1267.41
2891001357   1120.00

### Análise de sobrepeso nos usuários do fitbit
* 35 ids tem dados sobre peso
* 7 ids do fit estão acima do peso, e apenas 1 delas tem obesidade grau 2 e apenas 1 tem obesidade grau 3
* comparando weightlog e daily activity, 3 usuários acima do peso  tem inputs com total step zerado ,mas não todos os inputs de total steps zerados

Passar esse código para parte de tratamento de dados 

In [256]:
# Um pequeno tratamento nos dados aqui, mas não é o correto realizar aqui
# passa depois para um parte de processamento e tratamento dos dados, o CVs foi salvo com o nome
# weightLogInfo_merged_treated, isso facilita para criar graficos esse tratamento e também selecionar a coluna
# for index, linha in weightlog.iterrows():
#       BMI = linha['BMI']
#       if BMI < 18.5:
#             weightlog['BMI_describe'] = 'low weight'
#       elif BMI >=18.5 and BMI <= 24.9:
#             weightlog['BMI_describe'] = 'normal weight'
#       elif BMI >=25 and BMI <= 29.9:
#             weightlog['BMI_describe'] = 'overweight'
#       else:
#             weightlog['BMI_describe'] = 'obesity'


In [257]:
# #salvar o dataset com essa descrição, se possivel passar esse codigo para a parte de processamento e tratamento de dados
# weightlog.to_csv('weightLogInfo_merged_treated.csv', index= False)

In [258]:
overweight_ids = weightlog.loc[weightlog['BMI_describe'] == 'overweight', 'Id'].unique()

In [259]:
weightlog[weightlog['Id'].isin(overweight_ids)]

Id                   Date    WeightKg  WeightPounds   Fat  \
0   1503960366   4/5/2016 11:59:59 PM   53.299999    117.506384  22.0   
1   1927972279   4/10/2016 6:33:26 PM  129.600006    285.719105   NaN   
2   2347167796   4/3/2016 11:59:59 PM   63.400002    139.773078  10.0   
3   2873212765   4/6/2016 11:59:59 PM   56.700001    125.002104   NaN   
4   2873212765   4/7/2016 11:59:59 PM   57.200001    126.104416   NaN   
5   2891001357   4/5/2016 11:59:59 PM   88.400002    194.888643   NaN   
6   4445114986  3/30/2016 11:59:59 PM   92.400002    203.707134   NaN   
7   4558609924   4/8/2016 11:59:59 PM   69.400002    153.000813   NaN   
8   4702921684   4/4/2016 11:59:59 PM   99.699997    219.800869   NaN   
9   6962181067  3/30/2016 11:59:59 PM   61.500000    135.584291   NaN   
10  6962181067  3/31/2016 11:59:59 PM   61.500000    135.584291   NaN   
11  6962181067   4/1/2016 11:59:59 PM   60.900002    134.261521   NaN   
12  6962181067   4/2/2016 11:59:59 PM   61.200001    134.922906   NaN   
13  6962181067   4/3/2016 11:59:59 PM   61.500000    135.584291   NaN   
14  6962181067   4/4/2016 11:59:59 PM   62.400002    137.568455   NaN   
15  6962181067   4/5/2016 11:59:59 PM   61.700001    136.025217   NaN   
16  6962181067   4/6/2016 11:59:59 PM   62.200001    137.127529   NaN   
17  6962181067   4/7/2016 11:59:59 PM   62.200001    137.127529   NaN   
18  6962181067   4/8/2016 11:59:59 PM   61.700001    136.025217   NaN   
19  6962181067   4/9/2016 11:59:59 PM   62.099998    136.907061   NaN   
20  6962181067  4/10/2016 11:59:59 PM   62.500000    137.788914   NaN   
21  6962181067  4/11/2016 11:59:59 PM   62.200001    137.127529   NaN   
22  6962181067  4/12/2016 11:59:59 PM   62.500000    137.788914   NaN   
23  8253242879   4/7/2016 11:59:59 PM   75.599998    166.669467   NaN   
24  8877689391    4/1/2016 6:49:40 AM   85.500000    188.495234   NaN   
25  8877689391    4/4/2016 6:53:43 AM   86.599998    190.920316   NaN   
26  8877689391    4/5/2016 6:40:15 AM   86.000000    189.597545   NaN   
27  8877689391    4/6/2016 6:49:31 AM   86.300003    190.258939   NaN   
28  8877689391    4/7/2016 6:15:08 AM   85.099998    187.613382   NaN   
29  8877689391    4/8/2016 6:39:44 AM   85.000000    187.392923   NaN   
30  8877689391    4/9/2016 8:06:12 AM   85.400002    188.274775   NaN   
31  8877689391   4/11/2016 6:58:09 AM   86.099998    189.818004   NaN   
32  8877689391   4/12/2016 6:47:11 AM   85.800003    189.156628   NaN   

          BMI  IsManualReport          LogId BMI_describe  
0   22.969999            True  1459900799000   overweight  
1   46.169998           False  1460313206000   overweight  
2   24.770000            True  1459727999000   overweight  
3   21.450001            True  1459987199000   overweight  
4   21.650000            True  1460073599000   overweight  
5   25.030001            True  1459900799000   overweight  
6   35.009998            True  1459382399000   overweight  
7   27.139999            True  1460159999000   overweight  
8   26.110001            True  1459814399000   overweight  
9   24.030001            True  1459382399000   overweight  
10  24.030001            True  1459468799000   overweight  
11  23.780001            True  1459555199000   overweight  
12  23.889999            True  1459641599000   overweight  
13  24.030001            True  1459727999000   overweight  
14  24.350000            True  1459814399000   overweight  
15  24.100000            True  1459900799000   overweight  
16  24.280001            True  1459987199000   overweight  
17  24.280001            True  1460073599000   overweight  
18  24.100000            True  1460159999000   overweight  
19  24.240000            True  1460246399000   overweight  
20  24.389999            True  1460332799000   overweight  
21  24.280001            True  1460419199000   overweight  
22  24.389999            True  1460505599000   overweight  
23  29.549999            True  1460073599000   overweight  
24  25.610001           False

Apenas 7 id únicos pessoas dos dados usuárias do fit estão acima do peso, e apenas 1 delas tem obesidade grau 2 e apenas 1 tem obesidade grau 3

### Analisar os dados desse grupo amostral nos outros csv's

In [260]:
d_activity[(d_activity['TotalSteps']== 0) & (d_activity['Id'].isin(overweight_ids))] #3 usuários acima do peso  tem inputs com total step zerado

Id ActivityDate  TotalSteps  TotalDistance  TrackerDistance  \
122  2347167796    4/12/2016           0            0.0              0.0   
134  2873212765    4/12/2016           0            0.0              0.0   
135  2891001357    3/29/2016           0            0.0              0.0   
136  2891001357    3/30/2016           0            0.0              0.0   
137  2891001357    3/31/2016           0            0.0              0.0   
138  2891001357     4/1/2016           0            0.0              0.0   
140  2891001357     4/3/2016           0            0.0              0.0   
141  2891001357     4/4/2016           0            0.0              0.0   
290  4702921684    4/12/2016           0            0.0              0.0   
401  8253242879     4/1/2016           0            0.0              0.0   
402  8253242879     4/2/2016           0            0.0              0.0   
403  8253242879     4/3/2016           0            0.0              0.0   
404  8253242879     4/4/2016           0            0.0              0.0   
405  8253242879     4/5/2016           0            0.0              0.0   
412  8253242879    4/12/2016           0            0.0              0.0   

     LoggedActivitiesDistance  VeryActiveDistance  ModeratelyActiveDistance  \
122                  0.000000                 0.0                       0.0   
134                  0.000000                 0.0                       0.0   
135                  0.000000                 0.0                       0.0   
136                  0.000000                 0.0                       0.0   
137                  0.000000                 0.0                       0.0   
138                  4.828032                 0.0                       0.0   
140                  0.000000                 0.0                       0.0   
141                  0.000000                 0.0                       0.0   
290                  0.000000                 0.0                       0.0   
401                  0.000000                 0.0                       0.0   
402                  0.000000                 0.0                       0.0   
403                  0.000000                 0.0                       0.0   
404                  0.000000                 0.0                       0.0   
405                  0.000000                 0.0                       0.0   
412                  0.000000                 0.0                       0.0   

     LightActiveDistance  SedentaryActiveDistance  VeryActiveMinutes  \
122                  0.0                      0.0                  0   
134                  0.0                      0.0                  0   
135                  0.0                      0.0                  0   
136                  0.0                      0.0                  0   
137                  0.0                      0.0                  0   
138                  0.0                      0.0                  0   
140                  0.0                      0.0                  0   
141                  0.0                      0.0                  0   
290                  0.0                      0.0                  0   
401                  0.0                      0.0                  0   
402                  0.0                      0.0                  0   
403                  0.0                      0.0                  0   
404                  0.0                      0.0                  0   
405                  0.0                      0.0                  0   
412                  0.0                      0.0                  0   

     FairlyActiveMinutes  LightlyActiveMinutes  SedentaryMinutes  Calories  
122                    0                     0               425       399  
134                    0                     0              1440         0  
135                    0                     0              1440      1920  
136                    0                     0              1440      

### Analisar os usuarios que estão com peso normal são os que mais utilizaram o fitbit 

In [ ]:
# Analisar os usuarios que estão com peso normal se são os que mais utilizaram o fitbit de dailyactivity 


# insights até aqui