<h4><center>About Dataset</h4></center>
This dataset generated by respondents to a distributed survey via Amazon Mechanical Turk between 03.12.2016-05.12.2016. Thirty eligible Fitbit users consented to the submission of personal tracker data, including minute-level output for physical activity, heart rate, and sleep monitoring. Individual reports can be parsed by export session ID (column A) or timestamp (column B). Variation between output represents use of different types of Fitbit trackers and individual tracking behaviors / preferences.

<center><h3>Análise exploratória dados fitbit</center></h3>

In [1]:
import pandas as pd
from pathlib import Path

In [2]:
# This facilitates opening the file,  wihout needing to input all the file path, as there are two people coding in this project.
caminho_arquivo = Path('dailyActivity_merged.csv').resolve().parents[1]
print('caminho do diretório',caminho_arquivo)

caminho do diretório D:\python\bellabeat-analysis


In [3]:
d_activity = pd.read_csv(f'{caminho_arquivo}/database/fitbit-data/dailyActivity_merged.csv')
heartrate = pd.read_csv(f'{caminho_arquivo}/database/fitbit-data/heartrate_seconds_merged.csv')
h_calories = pd.read_csv(f'{caminho_arquivo}/database/fitbit-data/hourlyCalories_merged.csv')
h_intensity = pd.read_csv(f'{caminho_arquivo}/database/fitbit-data/hourlyIntensities_merged.csv')
m_calories = pd.read_csv(f'{caminho_arquivo}/database/fitbit-data/minuteCaloriesNarrow_merged.csv')
m_intensity = pd.read_csv(f'{caminho_arquivo}/database/fitbit-data/minuteIntensitiesNarrow_merged.csv')
m_sleep = pd.read_csv(f'{caminho_arquivo}//database/fitbit-data/minuteSleep_merged.csv')
weightlog = pd.read_csv(f'{caminho_arquivo}/database/fitbit-data/weightLogInfo_merged_treated.csv')

In [46]:
weightlog.sort_values(by='Id')

Id                   Date    WeightKg  WeightPounds   Fat  \
0   1503960366   4/5/2016 11:59:59 PM   53.299999    117.506384  22.0   
1   1927972279   4/10/2016 6:33:26 PM  129.600006    285.719105   NaN   
2   2347167796   4/3/2016 11:59:59 PM   63.400002    139.773078  10.0   
3   2873212765   4/6/2016 11:59:59 PM   56.700001    125.002104   NaN   
4   2873212765   4/7/2016 11:59:59 PM   57.200001    126.104416   NaN   
5   2891001357   4/5/2016 11:59:59 PM   88.400002    194.888643   NaN   
6   4445114986  3/30/2016 11:59:59 PM   92.400002    203.707134   NaN   
7   4558609924   4/8/2016 11:59:59 PM   69.400002    153.000813   NaN   
8   4702921684   4/4/2016 11:59:59 PM   99.699997    219.800869   NaN   
9   6962181067  3/30/2016 11:59:59 PM   61.500000    135.584291   NaN   
10  6962181067  3/31/2016 11:59:59 PM   61.500000    135.584291   NaN   
11  6962181067   4/1/2016 11:59:59 PM   60.900002    134.261521   NaN   
12  6962181067   4/2/2016 11:59:59 PM   61.200001    134.922906   NaN   
13  6962181067   4/3/2016 11:59:59 PM   61.500000    135.584291   NaN   
14  6962181067   4/4/2016 11:59:59 PM   62.400002    137.568455   NaN   
15  6962181067   4/5/2016 11:59:59 PM   61.700001    136.025217   NaN   
16  6962181067   4/6/2016 11:59:59 PM   62.200001    137.127529   NaN   
17  6962181067   4/7/2016 11:59:59 PM   62.200001    137.127529   NaN   
18  6962181067   4/8/2016 11:59:59 PM   61.700001    136.025217   NaN   
19  6962181067   4/9/2016 11:59:59 PM   62.099998    136.907061   NaN   
20  6962181067  4/10/2016 11:59:59 PM   62.500000    137.788914   NaN   
21  6962181067  4/11/2016 11:59:59 PM   62.200001    137.127529   NaN   
22  6962181067  4/12/2016 11:59:59 PM   62.500000    137.788914   NaN   
23  8253242879   4/7/2016 11:59:59 PM   75.599998    166.669467   NaN   
24  8877689391    4/1/2016 6:49:40 AM   85.500000    188.495234   NaN   
25  8877689391    4/4/2016 6:53:43 AM   86.599998    190.920316   NaN   
26  8877689391    4/5/2016 6:40:15 AM   86.000000    189.597545   NaN   
27  8877689391    4/6/2016 6:49:31 AM   86.300003    190.258939   NaN   
28  8877689391    4/7/2016 6:15:08 AM   85.099998    187.613382   NaN   
29  8877689391    4/8/2016 6:39:44 AM   85.000000    187.392923   NaN   
30  8877689391    4/9/2016 8:06:12 AM   85.400002    188.274775   NaN   
31  8877689391   4/11/2016 6:58:09 AM   86.099998    189.818004   NaN   
32  8877689391   4/12/2016 6:47:11 AM   85.800003    189.156628   NaN   

          BMI  IsManualReport          LogId   BMI_describe  
0   22.969999            True  1459900799000  Normal weight  
1   46.169998           False  1460313206000        Obesity  
2   24.770000            True  1459727999000  Normal weight  
3   21.450001            True  1459987199000  Normal weight  
4   21.650000            True  1460073599000  Normal weight  
5   25.030001            True  1459900799000     Overweight  
6   35.009998            True  1459382399000        Obesity  
7   27.139999            True  1460159999000     Overweight  
8   26.110001            True  1459814399000     Overweight  
9   24.030001            True  1459382399000  Normal weight  
10  24.030001            True  1459468799000  Normal weight  
11  23.780001            True  1459555199000  Normal weight  
12  23.889999            True  1459641599000  Normal weight  
13  24.030001            True  1459727999000  Normal weight  
14  24.350000            True  1459814399000  Normal weight  
15  24.100000            True  1459900799000  Normal weight  
16  24.280001            True  1459987199000  Normal weight  
17  24.280001            True  1460073599000  Normal weight  
18  24.100000            True  1460159999000  Normal weight  
19  24.240000            True  1460246399000  Normal weight  
20  24.389999            True  1460332799000  Normal weight  
21  24.280001            True  1460419199000  Normal weight  
22  24.389999            True  1460505599000  Normal weight  
23  29.549999            True  1460073599

### Análise de uso das features

In [4]:
user_count_d_activity = d_activity['Id'].nunique() # 35 ids usam
user_count_h_calories = h_calories['Id'].nunique() #34 ids usam
user_count_h_intensity = h_intensity['Id'].nunique() #34 ids usam
user_count_m_calories = m_calories['Id'].nunique() #34 ids
user_count_m_intensity = m_intensity['Id'].nunique() #34 ids usam
user_count_m_sleep = m_sleep['Id'].nunique() #23 ids usam
user_count_heartrate = heartrate['Id'].nunique() # 14 ids usam
user_count_weightlog = weightlog['Id'].nunique() #11 ids usam

In [5]:
mean_use_d_activity = d_activity['Id'].value_counts().mean().round(0)
mean_use_h_calories = h_calories['Id'].value_counts().mean().round(0)
mean_use_h_intensity = h_intensity['Id'].value_counts().mean().round(0)
mean_use_m_calories = m_calories['Id'].value_counts().mean().round(0)
mean_use_m_intensity = m_intensity['Id'].value_counts().mean().round(0)
mean_use_m_sleep = m_sleep['Id'].value_counts().mean().round(0)
mean_use_heartrate = heartrate['Id'].value_counts().mean().round(0)
mean_use_weightlog = weightlog['Id'].value_counts().mean().round(0)

In [6]:
print("Ids usando função 'daily activity':",user_count_d_activity,". Média de uso por Id:", mean_use_d_activity)
print("Ids usando função 'hourly calories':",user_count_h_calories ,". Média de uso por Id:",mean_use_h_calories )
print("Ids usando função 'hourly intensity':",user_count_h_intensity,". Média de uso por Id:", mean_use_h_intensity )
print("Ids usando função 'minute calories':",user_count_m_calories,". Média de uso por Id:", mean_use_m_calories)
print("Ids usando função 'minute intensity':",user_count_m_intensity,". Média de uso por Id:", mean_use_m_intensity)
print("Ids usando função 'minute sleep':",user_count_m_sleep,". Média de uso por Id:", mean_use_m_sleep)
print("Ids usando função 'heart rate':",user_count_heartrate,". Média de uso por Id:", mean_use_heartrate)
print("Ids usando função 'weightlog':",user_count_weightlog,". Média de uso por Id:", mean_use_weightlog)

Ids usando função 'daily activity': 35 . Média de uso por Id: 13.0
Ids usando função 'hourly calories': 34 . Média de uso por Id: 708.0
Ids usando função 'hourly intensity': 34 . Média de uso por Id: 708.0
Ids usando função 'minute calories': 34 . Média de uso por Id: 42501.0
Ids usando função 'minute intensity': 34 . Média de uso por Id: 42501.0
Ids usando função 'minute sleep': 23 . Média de uso por Id: 8633.0
Ids usando função 'heart rate': 14 . Média de uso por Id: 82477.0
Ids usando função 'weightlog': 11 . Média de uso por Id: 3.0


### Checagem de timeframe dos dados e presença dos ids ao longo do tempo

In [7]:
pd.pivot_table(d_activity, index='ActivityDate', values= 'Id', aggfunc='count').sort_values(by='ActivityDate', ascending= True)
# primeiras duas semanas dos dados só tem 2 usuários ativos, outros usuários se tornam ativos ao longo dos dias restantes
# 15 usos do fitbit por id deve levar em conta essa distribuição
# primeiro dia do dataframe: 12 de março . último dia do data frame: 12 de abril


Id
ActivityDate    
3/12/2016      2
3/13/2016      2
3/14/2016      2
3/15/2016      2
3/16/2016      2
3/17/2016      2
3/18/2016      2
3/19/2016      2
3/20/2016      2
3/21/2016      2
3/22/2016      2
3/23/2016      2
3/24/2016      2
3/25/2016      4
3/26/2016      4
3/27/2016      4
3/28/2016      4
3/29/2016     10
3/30/2016     11
3/31/2016     11
4/1/2016      34
4/10/2016     29
4/11/2016     25
4/12/2016     24
4/2/2016      35
4/3/2016      35
4/4/2016      35
4/5/2016      35
4/6/2016      33
4/7/2016      33
4/8/2016      33
4/9/2016      32

### Análise exploratória d_activity


In [8]:
d_activity.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 457 entries, 0 to 456
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Id                        457 non-null    int64  
 1   ActivityDate              457 non-null    object 
 2   TotalSteps                457 non-null    int64  
 3   TotalDistance             457 non-null    float64
 4   TrackerDistance           457 non-null    float64
 5   LoggedActivitiesDistance  457 non-null    float64
 6   VeryActiveDistance        457 non-null    float64
 7   ModeratelyActiveDistance  457 non-null    float64
 8   LightActiveDistance       457 non-null    float64
 9   SedentaryActiveDistance   457 non-null    float64
 10  VeryActiveMinutes         457 non-null    int64  
 11  FairlyActiveMinutes       457 non-null    int64  
 12  LightlyActiveMinutes      457 non-null    int64  
 13  SedentaryMinutes          457 non-null    int64  
 14  Calories  

In [9]:
# Existe 457 registros, mas 35 Ids unicos, Sempre que a pessoa usa o app o registro é salvo novamente.
# Isso é uma suposição, então se for analisar quantidade de atividade fisica por pessoa, tem  que juntar os id.
# Se for analisar a quantidade de que pessoa usa o app, junta quantas vezes tal id aparece.
# Apenas um exemplo
duplicados = d_activity['Id'].duplicated().sum()
duplicados


np.int64(422)

In [10]:
# Mostrando Ids duplicados, Então, sempre que a pessoa usa o app grava o dia e a data da atividade.
# existe apenas 35 pessoas que usam o app. 
duplicados = d_activity.duplicated(subset='Id')
print(d_activity[duplicados])

             Id ActivityDate  TotalSteps  TotalDistance  TrackerDistance  \
1    1503960366    3/26/2016       17609      11.550000        11.550000   
2    1503960366    3/27/2016       12736       8.530000         8.530000   
3    1503960366    3/28/2016       13231       8.930000         8.930000   
4    1503960366    3/29/2016       12041       7.850000         7.850000   
5    1503960366    3/30/2016       10970       7.160000         7.160000   
..          ...          ...         ...            ...              ...   
452  8877689391     4/8/2016       23014      20.389999        20.389999   
453  8877689391     4/9/2016       16470       8.070000         8.070000   
454  8877689391    4/10/2016       28497      27.530001        27.530001   
455  8877689391    4/11/2016       10622       8.060000         8.060000   
456  8877689391    4/12/2016        2350       1.780000         1.780000   

     LoggedActivitiesDistance  VeryActiveDistance  ModeratelyActiveDistance  \
1       

In [11]:
# Quantas vezes os 35 id aparecem, para saber frequência do uso da feature d_activity
contagem_id = d_activity['Id'].value_counts()
contagem_id.sort_values()

Id
4388161847     8
8583815059     8
2891001357     8
6391747486     9
6775888955     9
3372868164    10
6290855005    10
1644430081    10
6117666160    10
8053475328    11
5577150313    11
4319703577    12
4558609924    12
3977333714    12
2320127002    12
2873212765    12
7007744171    12
8877689391    12
7086361926    12
8253242879    12
8378563200    12
1927972279    12
2022484408    12
5553957443    12
2026352035    12
1844505072    12
8792009665    12
6962181067    14
2347167796    15
4702921684    15
4445114986    15
1503960366    19
1624580081    19
4020332650    32
4057192912    32
Name: count, dtype: int64

### Análise Total steps

#### Estatística dos dados de passos

In [12]:
d_activity['TotalSteps'].median() #5986.0
d_activity['TotalSteps'].mean() #6546.5
d_activity['TotalSteps'].mode() #0  61 linhas desse dataframe não tem nenhuma entrada de exercício, ou passos. 
#396 entradas com input de passos

0    0
Name: TotalSteps, dtype: int64

#### Análise de passos max e mean por id

In [13]:
pd.pivot_table(d_activity, values = 'TotalSteps', index= 'Id', aggfunc= ('mean', 'max')).round(2)
#apenas uma pessoa não fez input de passos, média e máximo de passos parece sem erros

max      mean
Id                         
1503960366  17609  11640.53
1624580081  18464   4226.26
1644430081  20237   9274.80
1844505072   6847   3640.58
1927972279   5662   2180.83
2022484408  18247  12174.92
2026352035   6679   3392.75
2320127002  11230   3138.42
2347167796  16081   9800.07
2873212765  14103   6636.58
2891001357   4126    773.62
3372868164   8827   6127.50
3977333714  15425   8663.92
4020332650  12483   5776.59
4057192912   8433   1887.22
4319703577  10946   7820.58
4388161847      0      0.00
4445114986   6911   4293.07
4558609924   8828   5785.25
4702921684  14002   7943.40
5553957443  15444   8354.75
5577150313  14873   8608.18
6117666160  19658   8248.60
6290855005   9548   1618.10
6391747486   9766   1336.89
6775888955  13987   5559.00
6962181067  18952  12639.71
7007744171  16806  12260.33
7086361926  14604   6103.92
8053475328  25701  14844.36
8253242879  12026   2389.92
8378563200  14179   8135.25
8583815059   6835   3045.50
8792009665   8452   3094.92
8877689391  28497  17417.08

In [14]:
d_activity[d_activity['TotalSteps']== 0] #dados nulos? é possível entender que essas pessoas só usam o fitbit em dias de exercício?

Id ActivityDate  TotalSteps  TotalDistance  TrackerDistance  \
51   1844505072     4/4/2016           0            0.0              0.0   
52   1844505072     4/5/2016           0            0.0              0.0   
59   1844505072    4/12/2016           0            0.0              0.0   
96   2320127002     4/1/2016           0            0.0              0.0   
97   2320127002     4/2/2016           0            0.0              0.0   
..          ...          ...         ...            ...              ...   
402  8253242879     4/2/2016           0            0.0              0.0   
403  8253242879     4/3/2016           0            0.0              0.0   
404  8253242879     4/4/2016           0            0.0              0.0   
405  8253242879     4/5/2016           0            0.0              0.0   
412  8253242879    4/12/2016           0            0.0              0.0   

     LoggedActivitiesDistance  VeryActiveDistance  ModeratelyActiveDistance  \
51                        0.0                 0.0                       0.0   
52                        0.0                 0.0                       0.0   
59                        0.0                 0.0                       0.0   
96                        0.0                 0.0                       0.0   
97                        0.0                 0.0                       0.0   
..                        ...                 ...                       ...   
402                       0.0                 0.0                       0.0   
403                       0.0                 0.0                       0.0   
404                       0.0                 0.0                       0.0   
405                       0.0                 0.0                       0.0   
412                       0.0                 0.0                       0.0   

     LightActiveDistance  SedentaryActiveDistance  VeryActiveMinutes  \
51                   0.0                      0.0                  0   
52                   0.0                      0.0                  0   
59                   0.0                      0.0                  0   
96                   0.0                      0.0                  0   
97                   0.0                      0.0                  0   
..                   ...                      ...                ...   
402                  0.0                      0.0                  0   
403                  0.0                      0.0                  0   
404                  0.0                      0.0                  0   
405                  0.0                      0.0                  0   
412                  0.0                      0.0                  0   

     FairlyActiveMinutes  LightlyActiveMinutes  SedentaryMinutes  Calories  
51                     0                     0               669      1347  
52                     0                     0              1440      1347  
59                     0                     0               426       399  
96                     0                     0              1440      1324  
97                     0                     0              1440      1324  
..                   ...                   ...               ...       ...  
402                    0                     0              1440      1429  
403                    0                     0              1440      1429  
404                    0                     0              1440      1429  
405                    0                     0              1440      1429  
412                    0                     0              1440         0  

[61 rows x 15 columns]

In [15]:
# pesquisando entradas dos ids com steps nulos - 14 pessoas com dados nulos de passos - sabendo que apenas um desses Ids (4388161847) não tem nenhum input de passos
null_steps_ids = d_activity.loc[d_activity['TotalSteps']== 0, 'Id'].drop_duplicates()
null_steps_ids
# Pelo menos 1 vez ou mais esses ids não tiveram entrada de steps.

51     1844505072
96     2320127002
122    2347167796
134    2873212765
135    2891001357
197    4057192912
240    4319703577
241    4388161847
290    4702921684
316    6117666160
326    6290855005
334    6391747486
346    6775888955
401    8253242879
Name: Id, dtype: int64

### Insights sobre steps até aqui:
* 34 Ids tem input de passos, sem dados discrepantes.
* um Id não inputou passos nenhuma vez.
* 14 ids tem pelo menos 1 ou masi de um dia com 0 passos, como não é viável passar 1 dia sem dar passos, pode-se supor que são pessoas que não usam o fit bit em dias sem exercício (e nessa amostra, são minoria)

In [16]:
# existe 14 ids com steps zero, mas todas as suas colunas nao estão com zero, saber qual contéudo das colunas dos ids com steps zro
id_a_verificar = [
    1844505072, 2320127002, 2347167796, 2873212765, 2891001357,
    4057192912, 4319703577, 4388161847, 4702921684, 6117666160,
    6290855005, 6391747486, 6775888955, 8253242879
]
for ids in id_a_verificar:
    print(f"Verificando se o ID {ids}")
    colunas_id = d_activity[d_activity['Id'] == ids].drop('Id', axis=1)
    
    # Check if all values in all columns (except 'Id') are zero
    todas_zeros = (colunas_id == 0).all().all()
    print("todas as suas colunas tem valor zero", todas_zeros)

Verificando se o ID 1844505072
todas as suas colunas tem valor zero False
Verificando se o ID 2320127002
todas as suas colunas tem valor zero False
Verificando se o ID 2347167796
todas as suas colunas tem valor zero False
Verificando se o ID 2873212765
todas as suas colunas tem valor zero False
Verificando se o ID 2891001357
todas as suas colunas tem valor zero False
Verificando se o ID 4057192912
todas as suas colunas tem valor zero False
Verificando se o ID 4319703577
todas as suas colunas tem valor zero False
Verificando se o ID 4388161847
todas as suas colunas tem valor zero False
Verificando se o ID 4702921684
todas as suas colunas tem valor zero False
Verificando se o ID 6117666160
todas as suas colunas tem valor zero False
Verificando se o ID 6290855005
todas as suas colunas tem valor zero False
Verificando se o ID 6391747486
todas as suas colunas tem valor zero False
Verificando se o ID 6775888955
todas as suas colunas tem valor zero False
Verificando se o ID 8253242879
todas a

In [17]:
# Ver contéudo das colunas desse ID 1844505072
d_activity[d_activity['Id']== 1844505072]

Id ActivityDate  TotalSteps  TotalDistance  TrackerDistance  \
48  1844505072     4/1/2016        6847           4.53             4.53   
49  1844505072     4/2/2016        5367           3.55             3.55   
50  1844505072     4/3/2016        2841           1.88             1.88   
51  1844505072     4/4/2016           0           0.00             0.00   
52  1844505072     4/5/2016           0           0.00             0.00   
53  1844505072     4/6/2016           7           0.00             0.00   
54  1844505072     4/7/2016        6344           4.19             4.19   
55  1844505072     4/8/2016        5316           3.51             3.51   
56  1844505072     4/9/2016        4979           3.29             3.29   
57  1844505072    4/10/2016        6556           4.34             4.34   
58  1844505072    4/11/2016        5430           3.59             3.59   
59  1844505072    4/12/2016           0           0.00             0.00   

    LoggedActivitiesDistance  VeryActiveDistance  ModeratelyActiveDistance  \
48                       0.0                0.61                      0.37   
49                       0.0                0.00                      0.00   
50                       0.0                0.00                      0.00   
51                       0.0                0.00                      0.00   
52                       0.0                0.00                      0.00   
53                       0.0                0.00                      0.00   
54                       0.0                0.00                      0.00   
55                       0.0                0.00                      0.00   
56                       0.0                0.00                      0.00   
57                       0.0                0.00                      0.00   
58                       0.0                0.00                      0.00   
59                       0.0                0.00                      0.00   

    LightActiveDistance  SedentaryActiveDistance  VeryActiveMinutes  \
48                 3.55                      0.0                  9   
49                 3.55                      0.0                  0   
50                 1.88                      0.0                  0   
51                 0.00                      0.0                  0   
52                 0.00                      0.0                  0   
53                 0.00                      0.0                  0   
54                 4.19                      0.0                  0   
55                 3.51                      0.0                  0   
56                 3.29                      0.0                  0   
57                 4.33                      0.0                  0   
58                 3.59                      0.0                  0   
59                 0.00                      0.0                  0   

    FairlyActiveMinutes  LightlyActiveMinutes  SedentaryMinutes  Calories  
48                    9                   251              1171      1969  
49                    0                   263              1177      1889  
50                    0                   136              1114      1636  
51                    0                     0               669      1347  
52                    0                     0              1440      1347  
53                    0                     1              1439      1349  
54                    0                   290              1150      1965  
55                    0                   221              1219      1824  
56                    0                   184               620      1807  
57                    0                   305               810      1971  
58                    0                   251              1189      1888  
59                    0                     0               426       399

In [18]:
# Quantas vezes o step zero aparece 
df_filtrado = d_activity[d_activity['TotalSteps'] == 0]
len(df_filtrado['TotalSteps'])
# Existe 61 valores com zero, pois dos 14 ids que tem step zero, somando da 61 steps zero, pois alguns ficaram 1 ou mais dias sem dar passos.

61

### Acrescentando infomação na Análise do  d_activity
* 14 ids tem dias com 0 passos, como não é viável passar 1 dia sem dar passos, <br>pode-se supor que são pessoas que não usam o fit bit em dias sem exercício <br>(e nessa amostra, são minoria)
desses 14 ids, alguns repetem com passos 0 em outros dias.
* Há um total de 61 registros com passados zeros, esses são os 14 ids que contém essa situação.

* Como a base tem 427 registros e 35 ids unicos foi verificado que <br>apenas 61 registros contém steps com 0.
Grande parte dos 35 ids costumam usam o app?  

* 35 ids unicos, 14 desses as vezes não deram passos 1 ou mais dias.  
a base total tem 457 linhas e apenas 61 estão com passos 0 no total dessas linhas. <br>
Então, 86.65 % da base tem steps preenchidos, o que significa que os id (pessoas) utilizam bastante o d_activity

### Análise exploratória heartrate

In [19]:
heartrate.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1154681 entries, 0 to 1154680
Data columns (total 3 columns):
 #   Column  Non-Null Count    Dtype 
---  ------  --------------    ----- 
 0   Id      1154681 non-null  int64 
 1   Time    1154681 non-null  object
 2   Value   1154681 non-null  int64 
dtypes: int64(2), object(1)
memory usage: 26.4+ MB


In [20]:
heartrate.head()

Id                 Time  Value
0  2022484408  4/1/2016 7:54:00 AM     93
1  2022484408  4/1/2016 7:54:05 AM     91
2  2022484408  4/1/2016 7:54:10 AM     96
3  2022484408  4/1/2016 7:54:15 AM     98
4  2022484408  4/1/2016 7:54:20 AM    100

In [21]:
heartrate['Id'].nunique() #14 ids com heartrate, menos que a metade dos dados de passos

14

In [22]:
# Total de linhas no data frame heartrate
contagem_linhas = heartrate.shape[0]  # Zero representa as linhas
contagem_linhas
# Tem bem mais registros que o dailyactivity
# Tem menos id unicos, mas a quantidade de linhas é maior que o dailyactivity, significa que é bastande utilziado por esses id ? 

1154681

In [23]:
pd.pivot_table(heartrate, values = 'Value', index= 'Id', aggfunc= ['mean', 'max', 'min']).round(2).sort_values(by= ('mean', 'Value'), ascending= False)

mean   max   min
            Value Value Value
Id                           
6775888955  97.74   185    59
7007744171  89.93   158    56
8877689391  87.60   179    47
6391747486  84.12   133    49
6117666160  83.49   130    52
4020332650  81.90   151    46
2022484408  81.69   182    46
6962181067  80.69   176    48
4558609924  79.55   158    50
8792009665  76.33   163    45
2347167796  76.07   182    51
5553957443  69.42   152    48
2026352035  65.78    80    57
5577150313  65.00   176    36

### Insights até aqui
* apenas 14 ids tem input de heart rate
* destes 14, 4 ids estão em comum com a lista de pessoas que teorizei que só usam durante exercício (6775888955 , 6391747486, 6117666160 , 2347167796), o que ainda pode fazer sentido, a valor médio de batimentos é alto em 3 delas - pode indicar novamente fitbit apenas quando faz exercício
* Tem menos ids e mais registros que o dailyActivit

* OBS ( Seria bom depois ver os ids que usa dailyactivit e ver quais ids são iguais que utiliza o heartrate, dos 14 ids, ver quais são esses do dailyactivit, pois ir juntando, pode ajudar a tirar alguma análise, da saúde deles )

In [24]:
# Quantas vezes os 14 id aparecem, para saber frequência do uso do app 
contagem_id = heartrate['Id'].value_counts()
contagem_id

Id
4020332650    283794
6962181067    125875
2347167796    120804
5553957443     97797
5577150313     87649
8877689391     85115
8792009665     70087
4558609924     69339
7007744171     64786
2022484408     56483
6117666160     53666
6775888955     35100
6391747486      3747
2026352035       439
Name: count, dtype: int64

### Análise exploratória hourly calories
* 34 ids tem input de calorias

In [25]:
h_calories.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24084 entries, 0 to 24083
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Id            24084 non-null  int64 
 1   ActivityHour  24084 non-null  object
 2   Calories      24084 non-null  int64 
dtypes: int64(2), object(1)
memory usage: 564.6+ KB


In [26]:
h_calories.head()

Id           ActivityHour  Calories
0  1503960366  3/12/2016 12:00:00 AM        48
1  1503960366   3/12/2016 1:00:00 AM        48
2  1503960366   3/12/2016 2:00:00 AM        48
3  1503960366   3/12/2016 3:00:00 AM        48
4  1503960366   3/12/2016 4:00:00 AM        48

In [27]:
h_calories['Id'].nunique() #34 ids com input de calorias (gastas)

34

In [28]:
h_calories['ActivityDay'] = h_calories['ActivityHour'].str.extract(r'^([^\s]+)')

daily_calories = pd.pivot_table(h_calories, values= 'Calories', index= ('Id', 'ActivityDay'), aggfunc= 'sum')
daily_calories

Calories
Id         ActivityDay          
1503960366 3/12/2016        2228
           3/13/2016        2100
           3/14/2016        1830
           3/15/2016        2111
           3/16/2016        1967
...                          ...
8877689391 4/5/2016         2832
           4/6/2016         4034
           4/7/2016         2941
           4/8/2016         4191
           4/9/2016         3835

[1021 rows x 1 columns]

In [29]:
avg_daily_calories = pd.pivot_table(daily_calories, values = 'Calories', index='Id', aggfunc= 'mean').round(2).sort_values(by='Calories', ascending= False)
avg_daily_calories

Calories
Id                  
8877689391   3435.25
5577150313   3434.71
8378563200   3338.84
4702921684   2957.23
1644430081   2956.90
8053475328   2941.59
6290855005   2652.27
4020332650   2633.62
6775888955   2631.03
7007744171   2609.22
1927972279   2580.94
2022484408   2568.50
7086361926   2292.34
8583815059   2286.64
6117666160   2270.83
4445114986   2192.34
6962181067   2170.50
4319703577   2144.29
2347167796   2093.41
1503960366   1945.94
2873212765   1906.90
8792009665   1901.50
3372868164   1900.03
4057192912   1895.72
6391747486   1805.21
5553957443   1767.94
4558609924   1764.34
8253242879   1495.13
1844505072   1471.81
2026352035   1452.91
2320127002   1444.88
1624580081   1384.22
3977333714   1267.41
2891001357   1120.00

### Análise de sobrepeso nos usuários do fitbit
* 35 ids tem dados sobre peso
* 7 ids do fit estão acima do peso, e apenas 1 delas tem obesidade grau 2 e apenas 1 tem obesidade grau 3
* comparando weightlog e daily activity, 3 usuários acima do peso  tem inputs com total step zerado ,mas não todos os inputs de total steps zerados

In [30]:
overweight_ids = weightlog.loc[weightlog['BMI_describe'] == 'overweight', 'Id'].unique()

In [31]:
weightlog.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Id              33 non-null     int64  
 1   Date            33 non-null     object 
 2   WeightKg        33 non-null     float64
 3   WeightPounds    33 non-null     float64
 4   Fat             2 non-null      float64
 5   BMI             33 non-null     float64
 6   IsManualReport  33 non-null     bool   
 7   LogId           33 non-null     int64  
 8   BMI_describe    33 non-null     object 
dtypes: bool(1), float64(4), int64(2), object(2)
memory usage: 2.2+ KB


In [32]:
weightlog[weightlog['Id'].isin(overweight_ids)]

Empty DataFrame
Columns: [Id, Date, WeightKg, WeightPounds, Fat, BMI, IsManualReport, LogId, BMI_describe]
Index: []

### Analisar os dados desse grupo amostral nos outros csv's

3 ids unicos com step zero estão com sobre peso 

In [33]:
d_activity_overweight_ids = d_activity[(d_activity['TotalSteps']== 0) & (d_activity['Id'].isin(overweight_ids))] #5 usuários acima do peso  tem inputs com total step zerado
id_overwigth = d_activity_overweight_ids.drop_duplicates('Id')
id_overwigth

Empty DataFrame
Columns: [Id, ActivityDate, TotalSteps, TotalDistance, TrackerDistance, LoggedActivitiesDistance, VeryActiveDistance, ModeratelyActiveDistance, LightActiveDistance, SedentaryActiveDistance, VeryActiveMinutes, FairlyActiveMinutes, LightlyActiveMinutes, SedentaryMinutes, Calories]
Index: []

Ver se os 5 ids com step 0 e sobrepeso foram os que menos se exercitaram dentre os demais id 

In [34]:
# Verificar quantas vezes esses ids com step zero e sobre preso de exercitaram  e quantas vezes essa foi step zero
id_overwigth_exercise_often = 2891001357, 4702921684, 2891001357, 8253242879 
d_activity_filter = d_activity[d_activity['Id'].isin(id_overwigth_exercise_often)]
sum_ativ = d_activity_filter['Id'].value_counts()
print('total de atividades que os ids que tem steps  e sobrepeso zeros fizeram',sum_ativ)
d_activity_step_zero_overweigh = d_activity_filter[(d_activity_filter['TotalSteps']== 0)]
sum_step_ac_zero = d_activity_step_zero_overweigh['Id'].value_counts()
print('total de vezes que o step foi zero dos que tem sobrepeso que os ids que tem steps zeros fizeram',sum_step_ac_zero)

total de atividades que os ids que tem steps  e sobrepeso zeros fizeram Id
4702921684    15
8253242879    12
2891001357     8
Name: count, dtype: int64
total de vezes que o step foi zero dos que tem sobrepeso que os ids que tem steps zeros fizeram Id
2891001357    6
8253242879    6
4702921684    1
Name: count, dtype: int64


### Análise de sobrepeso nos usuários do fitbit
* os 3 id que tem step zerados e estão com sobrepreso tem steps sem está zerado, <br> porém a quantidade de zerados é maior, o que indica que não exercitaram com frequência ?
(obs) alguns ids com sobrepreso e steps zerados não aparecem no heartrate, isso colabora para o sobrepreso ? 
* Como é peso daqueles que na tem steps zeros e que constumam ter uma frequencia alta no d_activy ? eles utilizam as demais funcionalidades com frequência também ?

In [35]:
# ids que tem bastante frequência no d_activiy 
# Vamos ver o peso desses id
id_overwigth_ = 4057192912, 4020332650, 1503960366, 1624580081  
"""""""""""
4057192912    32
4020332650    32
1503960366    19
1624580081    19
"""""""""""
weightlog_ids_wigth = weightlog[weightlog['Id'].isin(id_overwigth_)]
weightlog_ids_wigth

Id                  Date   WeightKg  WeightPounds   Fat        BMI  \
0  1503960366  4/5/2016 11:59:59 PM  53.299999    117.506384  22.0  22.969999   

   IsManualReport          LogId   BMI_describe  
0            True  1459900799000  Normal weight

### Análise exercício

In [36]:
pd.pivot_table(d_activity, values= ('Calories','VeryActiveMinutes','FairlyActiveMinutes','LightlyActiveMinutes'), index= 'Id',
               aggfunc={'Calories':'mean', 'VeryActiveMinutes': 'mean','FairlyActiveMinutes':'mean','LightlyActiveMinutes':'mean'}).sort_values(by='Calories', ascending=False).round(2)
# é possível observar que a maioria dos usuários do fitbit se exercitam mais por meio de "lightlyActiveMinutes"

Calories  FairlyActiveMinutes  LightlyActiveMinutes  \
Id                                                                
8877689391   3451.17                15.08                241.00   
8378563200   3356.17                10.33                168.92   
5577150313   3300.27                28.18                157.27   
4020332650   3075.38                 7.66                130.38   
1644430081   2916.40                43.50                227.70   
8053475328   2893.18                11.36                154.36   
4702921684   2821.47                17.27                246.73   
6775888955   2724.78                49.22                124.00   
7007744171   2627.08                16.25                277.50   
2022484408   2475.33                22.50                253.83   
8583815059   2391.25                 1.88                137.12   
2891001357   2273.38                82.50                168.75   
1927972279   2254.00                 1.67                111.67   
7086361926   2177.00                17.67                101.25   
6290855005   2165.60                10.70                 39.30   
4445114986   2107.80                 0.93                200.60   
6117666160   2099.30                 4.10                299.90   
6962181067   2089.21                29.00                258.57   
8792009665   2073.67                 5.42                132.08   
2347167796   2021.33                23.13                253.53   
4319703577   1994.25                18.25                248.67   
4057192912   1903.53                 5.28                 43.25   
3372868164   1860.30                 3.50                286.90   
4558609924   1830.17                 2.75                249.83   
4388161847   1805.25                 0.00                  0.00   
5553957443   1802.50                16.67                183.33   
1503960366   1796.21                15.84                228.21   
6391747486   1763.11                 0.67                 34.33   
2873212765   1695.75                 6.00                275.25   
1844505072   1615.92                 0.75                158.50   
2320127002   1532.08                 1.08                125.92   
8253242879   1463.00                 4.67                 59.25   
3977333714   1398.08                31.25                206.92   
2026352035   1355.50                 0.00                169.33   
1624580081   1352.89                 0.58                121.05   

            VeryActiveMinutes  
Id                             
8877689391              66.83  
8378563200              55.42  
5577150313              81.82  
4020332650               4.06  
1644430081              14.80  
8053475328              84.82  
4702921684               2.93  
6775888955              19.89  
7007744171              44.67  
2022484408              40.08  
8583815059               0.62  
2891001357               0.00  
1927972279               0.00  
7086361926              26.25  
6290855005               7.80  
4445114986               5.07  
6117666160               0.50  
6962181067              35.36  
8792009665               1.50  
2347167796              11.80  
4319703577               6.58  
4057192912               1.25  
3372868164              11.80  
4558609924               4.33  
4388161847               0.00  
5553957443              23.58  
1503960366              35.84  
6391747486               5.11  
2873212765               5.08  
1844505072               0.75  
2320127002               0.92  
8253242879               5.83  
3977333714              12.17  
2026352035               0.00  
1624580081               0.74

In [37]:
pd.pivot_table(d_activity, values= ('Calories', 'VeryActiveDistance', 'ModeratelyActiveDistance', 'LightActiveDistance'), index= 'Id',
               aggfunc={'Calories':'mean', 'VeryActiveDistance':'mean', 'ModeratelyActiveDistance':'mean','LightActiveDistance':'mean'}).sort_values(by='Calories', ascending=False).round(2)

Calories  LightActiveDistance  ModeratelyActiveDistance  \
Id                                                                    
8877689391   3451.17                 6.27                      0.48   
8378563200   3356.17                 3.96                      0.53   
5577150313   3300.27                 2.68                      0.65   
4020332650   3075.38                 2.24                      0.20   
1644430081   2916.40                 3.58                      2.03   
8053475328   2893.18                 2.54                      0.49   
4702921684   2821.47                 5.39                      0.81   
6775888955   2724.78                 1.82                      1.18   
7007744171   2627.08                 4.66                      0.66   
2022484408   2475.33                 4.81                      0.88   
8583815059   2391.25                 2.23                      0.09   
2891001357   2273.38                 0.60                      0.00   
1927972279   2254.00                 1.45                      0.06   
7086361926   2177.00                 1.99                      0.55   
6290855005   2165.60                 0.65                      0.37   
4445114986   2107.80                 2.44                      0.04   
6117666160   2099.30                 5.91                      0.27   
6962181067   2089.21                 4.28                      1.78   
8792009665   2073.67                 1.82                      0.11   
2347167796   2021.33                 4.39                      1.26   
4319703577   1994.25                 4.08                      0.72   
4057192912   1903.53                 1.04                      0.24   
3372868164   1860.30                 3.35                      0.11   
4558609924   1830.17                 3.53                      0.11   
4388161847   1805.25                 0.00                      0.00   
5553957443   1802.50                 3.08                      0.87   
1503960366   1796.21                 4.18                      0.64   
6391747486   1763.11                 0.84                      0.01   
2873212765   1695.75                 3.88                      0.26   
1844505072   1615.92                 2.32                      0.03   
2320127002   1532.08                 2.00                      0.04   
8253242879   1463.00                 0.79                      0.28   
3977333714   1398.08                 3.59                      1.37   
2026352035   1355.50                 2.10                      0.00   
1624580081   1352.89                 2.66                      0.03   

            VeryActiveDistance  
Id                              
8877689391                7.28  
8378563200                1.97  
5577150313                3.11  
4020332650                0.17  
1644430081                1.13  
8053475328                8.54  
4702921684                0.24  
6775888955                0.94  
7007744171                3.54  
2022484408                3.09  
8583815059                0.05  
2891001357                0.00  
1927972279                0.00  
7086361926                1.53  
6290855005                0.20  
4445114986                0.42  
6117666160                0.04  
6962181067                2.58  
8792009665                0.05  
2347167796                0.86  
4319703577                0.46  
4057192912                0.10  
3372868164                0.74  
4558609924                0.18  
4388161847                0.00  
5553957443                1.51  
1503960366                2.78  
6391747486                0.23  
2873212765                0.33  
1844505072                0.05  
2320127002                0.08  
8253242879                0.60  
3977333714                0.84  
2026352035                0.00  
1624580081                0.05

### Obesidade vs exercício

##### tentativa de comparar gasto calorico com peso, mas tem uma separação quase perfeita entre acima do gasto médio de calorias serem ids acima do peso e abaixo da média ids com imc normal (com 2 exceções). porém perfeito demais? 

##### Description: Estimated energy expenditure. <br> Note: Fitbit uses the gender, age, height, and weight data entered into the user profile to<br>calculate basal metabolic rate (BMR). The estimated energy expenditure that Fitbit provides<br>takes into account the user’s BMR, the activity recorded by the device, and any manually logged<br>activities.

### Tentar com total distance ao invés de calories

In [38]:
mean_distance = d_activity['TotalDistance'].mean() #4.6km

In [39]:
mean_distance_id = pd.pivot_table(d_activity, values = 'TotalDistance', index= 'Id', aggfunc= 'mean').round(1)

In [40]:
def avaliar_dist(value):
    if value > mean_distance:
        return "High average distance"
    else:
        return "Low average distance"

In [41]:
weightlog_BMI = weightlog[['Id' ,'BMI_describe']]
weightlog_BMI

Id   BMI_describe
0   1503960366  Normal weight
1   1927972279        Obesity
2   2347167796  Normal weight
3   2873212765  Normal weight
4   2873212765  Normal weight
5   2891001357     Overweight
6   4445114986        Obesity
7   4558609924     Overweight
8   4702921684     Overweight
9   6962181067  Normal weight
10  6962181067  Normal weight
11  6962181067  Normal weight
12  6962181067  Normal weight
13  6962181067  Normal weight
14  6962181067  Normal weight
15  6962181067  Normal weight
16  6962181067  Normal weight
17  6962181067  Normal weight
18  6962181067  Normal weight
19  6962181067  Normal weight
20  6962181067  Normal weight
21  6962181067  Normal weight
22  6962181067  Normal weight
23  8253242879     Overweight
24  8877689391     Overweight
25  8877689391     Overweight
26  8877689391     Overweight
27  8877689391     Overweight
28  8877689391     Overweight
29  8877689391     Overweight
30  8877689391     Overweight
31  8877689391     Overweight
32  8877689391     Overweight

In [42]:
distance_BMI = mean_distance_id.merge(weightlog_BMI, on='Id', how = 'left')
distance_BMI

Id  TotalDistance   BMI_describe
0   1503960366            7.6  Normal weight
1   1624580081            2.7            NaN
2   1644430081            6.7            NaN
3   1844505072            2.4            NaN
4   1927972279            1.5        Obesity
5   2022484408            8.8            NaN
6   2026352035            2.1            NaN
7   2320127002            2.1            NaN
8   2347167796            6.5  Normal weight
9   2873212765            4.5  Normal weight
10  2873212765            4.5  Normal weight
11  2891001357            0.6     Overweight
12  3372868164            4.2            NaN
13  3977333714            5.8            NaN
14  4020332650            4.1            NaN
15  4057192912            1.4            NaN
16  4319703577            5.3            NaN
17  4388161847            0.0            NaN
18  4445114986            2.9        Obesity
19  4558609924            3.8     Overweight
20  4702921684            6.4     Overweight
21  5553957443            5.5            NaN
22  5577150313            6.4            NaN
23  6117666160            6.2            NaN
24  6290855005            1.2            NaN
25  6391747486            1.1            NaN
26  6775888955            4.0            NaN
27  6962181067            8.6  Normal weight
28  6962181067            8.6  Normal weight
29  6962181067            8.6  Normal weight
30  6962181067            8.6  Normal weight
31  6962181067            8.6  Normal weight
32  6962181067            8.6  Normal weight
33  6962181067            8.6  Normal weight
34  6962181067            8.6  Normal weight
35  6962181067            8.6  Normal weight
36  6962181067            8.6  Normal weight
37  6962181067            8.6  Normal weight
38  6962181067            8.6  Normal weight
39  6962181067            8.6  Normal weight
40  6962181067            8.6  Normal weight
41  7007744171            8.9            NaN
42  7086361926            4.1            NaN
43  8053475328           11.6            NaN
44  8253242879            1.7     Overweight
45  8378563200            6.5            NaN
46  8583815059            2.4            NaN
47  8792009665            2.0            NaN
48  8877689391           14.1     Overweight
49  8877689391           14.1     Overweight
50  8877689391           14.1     Overweight
51  8877689391           14.1     Overweight
52  8877689391           14.1     Overweight
53  8877689391           14.1     Overweight
54  8877689391           14.1     Overweight
55  8877689391           14.1     Overweight
56  8877689391           14.1     Overweight

In [43]:
distance_BMI['DistanceEval'] = distance_BMI['TotalDistance'].apply(avaliar_dist)
distance_BMI.drop_duplicates()

Id  TotalDistance   BMI_describe           DistanceEval
0   1503960366            7.6  Normal weight  High average distance
1   1624580081            2.7            NaN   Low average distance
2   1644430081            6.7            NaN  High average distance
3   1844505072            2.4            NaN   Low average distance
4   1927972279            1.5        Obesity   Low average distance
5   2022484408            8.8            NaN  High average distance
6   2026352035            2.1            NaN   Low average distance
7   2320127002            2.1            NaN   Low average distance
8   2347167796            6.5  Normal weight  High average distance
9   2873212765            4.5  Normal weight   Low average distance
11  2891001357            0.6     Overweight   Low average distance
12  3372868164            4.2            NaN   Low average distance
13  3977333714            5.8            NaN  High average distance
14  4020332650            4.1            NaN   Low average distance
15  4057192912            1.4            NaN   Low average distance
16  4319703577            5.3            NaN  High average distance
17  4388161847            0.0            NaN   Low average distance
18  4445114986            2.9        Obesity   Low average distance
19  4558609924            3.8     Overweight   Low average distance
20  4702921684            6.4     Overweight  High average distance
21  5553957443            5.5            NaN  High average distance
22  5577150313            6.4            NaN  High average distance
23  6117666160            6.2            NaN  High average distance
24  6290855005            1.2            NaN   Low average distance
25  6391747486            1.1            NaN   Low average distance
26  6775888955            4.0            NaN   Low average distance
27  6962181067            8.6  Normal weight  High average distance
41  7007744171            8.9            NaN  High average distance
42  7086361926            4.1            NaN   Low average distance
43  8053475328           11.6            NaN  High average distance
44  8253242879            1.7     Overweight   Low average distance
45  8378563200            6.5            NaN  High average distance
46  8583815059            2.4            NaN   Low average distance
47  8792009665            2.0            NaN   Low average distance
48  8877689391           14.1     Overweight  High average distance

In [44]:
pd.crosstab(index= distance_BMI['BMI_describe'], columns= distance_BMI['DistanceEval'])

DistanceEval   High average distance  Low average distance
BMI_describe                                              
Normal weight                     16                     2
Obesity                            0                     2
Overweight                        10                     3

### Poucos Ids com dados no weightlog para tirar qualquer conclusão sobre exercício em relação ao IMC